### ISSUE TITLE
The telegraph is broken, kanjut.

### ISSUE THREAD

**Issue by NeofetchNpc** [IRON-M4N/ironman-api#2]
[ironman-api] error: Request failed with status code 400
file:///home/runner/work/NeastooAPI/NeastooAPI/node_modules/ironman-api/src/script.mjs:132
									throw new Error(String(error_2));
									      ^
Error: AxiosError: Request failed with status code 400
    at file:///home/runner/work/NeastooAPI/NeastooAPI/node_modules/ironman-api/src/script.mjs:132:16
    at step (file:///home/runner/work/NeastooAPI/NeastooAPI/node_modules/ironman-api/src/script.mjs:43:16)
    at Object.throw (file:///home/runner/work/NeastooAPI/NeastooAPI/node_modules/ironman-api/src/script.mjs:24:50)
    at rejected (file:///home/runner/work/NeastooAPI/NeastooAPI/node_modules/ironman-api/src/script.mjs:16:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v20.18.0
Error: Process completed with exit code 1.

**Comment by IRON-M4N** [comment]
Telegraph doesn't allow uploading anymore

**Comment by NeofetchNpc** [comment]
> Telegraph doesn't allow uploading anymore

use my uploader 
https://github.com/NeofetchNpc/ArchiveTMP

**Comment by IRON-M4N** [comment]
Thanks but i have my own, telegraph is gone so i might change it soon or not
